git-sd: Clean up the git-dir search
The search for a .git directory was done programmatically, while the
git-rev-parse command has the --git-dir option to perform this
operation.

diff --git a/bin/git-sd b/bin/git-sd
--- a/bin/git-sd
+++ b/bin/git-sd
@@ -2,21 +2,18 @@
 
 replica=`git config --get sd.local-replica`
 if [ -z "$replica" ]; then
-    if [ -z "$GIT_DIR" ] ; then # GIT_DIR Not defined
-        gitdir=`pwd`
-        while ! [ -e "$gitdir/.git" ]; do
-            if [ "$gitdir" = "/" ]; then
-                echo "Can't find a .git directory anywhere in your current directory"
-                echo "or any higher directories."
-                exit 1;
-            fi
-            gitdir=`dirname $gitdir`
-        done
-    else
-        gitdir="$GIT_DIR"
+    gitdir=$(git rev-parse --git-dir 2>/dev/null)
+    if [ -z "$gitdir" ]; then
+	echo "Can't find a .git directory anywhere in your current directory"
+	echo "or any higher directories."
+	exit 1;
     fi
-
-    replica="$gitdir/.git/sd"
+    # Special case: when in the toplevel directory, rev-parse --git-dir only
+    # returns '.git' instead of the full path.
+    if [ "$gitdir" = ".git" ]; then
+	gitdir="$(pwd)/.git"
+    fi
+    replica="$gitdir/sd"
     echo "You don't appear to have an sd.local-replica defined in your .git/config"
     echo "Setting it to '$replica':"
     echo ""
